spring:
  application:
    name: demomic-product
  config:
    import: optional:configserver:http://demomic-config:9000
  jpa.hibernate.ddl-auto: create-drop

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,env"
