server:
  port: 8088
  tomcat:
    threads:
      max: 50
      min-spare: 10

spring:
  config:
    import: optional:configserver:http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8070/eureka/

demomic-product:
  greetingMessage: "Some message"
